# 1. Cloud Billing Data Ingestion & Cleaning
This notebook handles raw billing logs, inspects schema integrity, imputes missing values, and drops unnecessary metadata columns (such as unique resource IDs and raw timestamps) to prepare the data for downstream machine learning.

In [48]:
import os
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

# 1. Create the database engine
# Format: postgresql://username:password@host:port/database_name
engine = create_engine(
    "postgresql://postgres:arnav2416@localhost:5432/cloud_resource_db"
)

# 2. Open a connection and run your query
with engine.connect() as conn:
    # Read data straight into a Pandas DataFrame
    df = pd.read_sql_query("SELECT * FROM cloud_billing_logs", conn)

print("Raw Dataset Shape:", df.shape)
df.head()

Raw Dataset Shape: (124275, 16)

,id,resource_id,service_name,usage_quantity,usage_unit,region_zone,cpu_utilization,memory_utilization,network_inbound_bytes,network_outbound_bytes,usage_start_time,usage_end_time,cost_per_quantity,unrounded_cost,rounded_cost,total_cost_inr
0,1,resource_433,Artifact Registry,78.4386,GB,asia-east1,93.44,82.65,4.442680e+11,4.446790e+11,2022-01-01,2022-01-04 13:00:00,1.9891,156.0222,156,12948
1,2,resource_155,Dialogflow,192.0000,Requests,asia-south1,59.39,75.17,8.943070e+11,8.948060e+11,2022-01-01,2022-01-09 01:00:00,8.8297,1695.3024,1695,140685
2,3,resource_934,Cloud Pub/Sub,313.0000,Requests,us-west1,71.72,83.31,1.967470e+11,1.975320e+11,2022-01-01,2022-01-06 22:00:00,7.4046,2317.6398,2318,192394
3,4,resource_511,Cloud Armor,262.0000,Requests,us-central1,86.48,27.19,8.712617e+10,8.792112e+10,2022-01-01,2022-01-05 07:00:00,9.1351,2393.3962,2393,198619
4,5,resource_666,Cloud Tasks,232.0000,Requests,asia-east1,99.56,51.72,4.219470e+11,4.220110e+11,2022-01-01,2022-01-03 15:00:00,4.7032,1091.1424,1091,90553

In [49]:
df.describe()

,id,usage_quantity,cpu_utilization,memory_utilization,network_inbound_bytes,network_outbound_bytes,usage_start_time,usage_end_time,cost_per_quantity,unrounded_cost,rounded_cost,total_cost_inr
count,124275.000000,124275.000000,124275.000000,124275.000000,1.242750e+05,1.242750e+05,124275,124275,124275.000000,124275.000000,124275.000000,1.242750e+05
mean,62138.000000,281.140043,50.044533,50.009794,4.999577e+11,5.004582e+11,2022-12-29 02:37:05.873265408,2023-01-03 20:54:44.306578432,5.056600,1419.920349,1419.920595,1.178534e+05
min,1.000000,1.000000,0.000000,0.000000,1.001984e+09,1.183427e+09,2022-01-01 00:00:00,2022-01-01 11:00:00,0.100100,0.138200,0.000000,0.000000e+00
25%,31069.500000,54.430400,24.865000,24.960000,2.490750e+11,2.495770e+11,2022-07-01 05:00:00,2022-07-07 05:00:00,2.568450,190.152550,190.000000,1.577000e+04
50%,62138.000000,129.000000,50.120000,49.930000,4.997240e+11,5.001940e+11,2022-12-28 22:00:00,2023-01-03 14:00:00,5.054200,557.242000,557.000000,4.623100e+04
75%,93206.500000,477.000000,75.140000,75.150000,7.499020e+11,7.503875e+11,2023-06-28 13:00:00,2023-07-04 00:00:00,7.545300,1915.782050,1916.000000,1.590280e+05
max,124275.000000,1699.000000,100.000000,100.000000,9.999830e+11,1.000860e+12,2023-12-30 19:00:00,2023-12-31 00:00:00,9.999900,13990.773600,13991.000000,1.161253e+06
std,35875.246689,292.984368,28.917505,28.932216,2.889701e+11,2.889707e+11,NaN,NaN,2.862321,1881.109525,1881.108874,1.561320e+05

In [50]:
df.columns

Index(['id', 'resource_id', 'service_name', 'usage_quantity', 'usage_unit',
       'region_zone', 'cpu_utilization', 'memory_utilization',
       'network_inbound_bytes', 'network_outbound_bytes', 'usage_start_time',
       'usage_end_time', 'cost_per_quantity', 'unrounded_cost', 'rounded_cost',
       'total_cost_inr'],
      dtype='object')

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124275 entries, 0 to 124274
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      124275 non-null  int64
 1   resource_id             124275 non-null  object
 2   service_name            124275 non-null  object
 3   usage_quantity          124275 non-null  float64
 4   usage_unit              124275 non-null  object
 5   region_zone             124275 non-null  object
 6   cpu_utilization         124275 non-null  float64
 7   memory_utilization      124275 non-null  float64
 8   network_inbound_bytes   124275 non-null  float64
 9   network_outbound_bytes  124275 non-null  float64
 10  usage_start_time        124275 non-null  datetime64[ns]
 11  usage_end_time          124275 non-null  datetime64[ns]
 12  cost_per_quantity       124275 non-null  float64
 13  unrounded_cost          124275 non-null  float64
 14  rounded_cost            124275 non-null  int64
 15  total_cost_inr          124275 non-null  int64
dtypes: datetime64[ns](2), float64(7), int64(3), object(4)
memory usage: 15.2+ MB

In [52]:
df.isnull().sum()

id                        0
resource_id               0
service_name              0
usage_quantity            0
usage_unit                0
region_zone               0
cpu_utilization           0
memory_utilization        0
network_inbound_bytes     0
network_outbound_bytes    0
usage_start_time          0
usage_end_time            0
cost_per_quantity         0
unrounded_cost            0
rounded_cost              0
total_cost_inr            0
dtype: int64

In [53]:
df['resource_id'] = df['resource_id'].str.split("_").str[1]
df.head()

,id,resource_id,service_name,usage_quantity,usage_unit,region_zone,cpu_utilization,memory_utilization,network_inbound_bytes,network_outbound_bytes,usage_start_time,usage_end_time,cost_per_quantity,unrounded_cost,rounded_cost,total_cost_inr
0,1,433,Artifact Registry,78.4386,GB,asia-east1,93.44,82.65,4.442680e+11,4.446790e+11,2022-01-01,2022-01-04 13:00:00,1.9891,156.0222,156,12948
1,2,155,Dialogflow,192.0000,Requests,asia-south1,59.39,75.17,8.943070e+11,8.948060e+11,2022-01-01,2022-01-09 01:00:00,8.8297,1695.3024,1695,140685
2,3,934,Cloud Pub/Sub,313.0000,Requests,us-west1,71.72,83.31,1.967470e+11,1.975320e+11,2022-01-01,2022-01-06 22:00:00,7.4046,2317.6398,2318,192394
3,4,511,Cloud Armor,262.0000,Requests,us-central1,86.48,27.19,8.712617e+10,8.792112e+10,2022-01-01,2022-01-05 07:00:00,9.1351,2393.3962,2393,198619
4,5,666,Cloud Tasks,232.0000,Requests,asia-east1,99.56,51.72,4.219470e+11,4.220110e+11,2022-01-01,2022-01-03 15:00:00,4.7032,1091.1424,1091,90553

In [54]:
# Convert bytes to Gigabytes (GB)
df['network_inbound_GB'] = df['network_inbound_bytes'] / (10**9)
df['network_outbound_GB'] = df['network_outbound_bytes'] / (10**9)

In [55]:
df.head()

,id,resource_id,service_name,usage_quantity,usage_unit,region_zone,cpu_utilization,memory_utilization,network_inbound_bytes,network_outbound_bytes,usage_start_time,usage_end_time,cost_per_quantity,unrounded_cost,rounded_cost,total_cost_inr,network_inbound_GB,network_outbound_GB
0,1,433,Artifact Registry,78.4386,GB,asia-east1,93.44,82.65,4.442680e+11,4.446790e+11,2022-01-01,2022-01-04 13:00:00,1.9891,156.0222,156,12948,444.26800,444.679000
1,2,155,Dialogflow,192.0000,Requests,asia-south1,59.39,75.17,8.943070e+11,8.948060e+11,2022-01-01,2022-01-09 01:00:00,8.8297,1695.3024,1695,140685,894.30700,894.806000
2,3,934,Cloud Pub/Sub,313.0000,Requests,us-west1,71.72,83.31,1.967470e+11,1.975320e+11,2022-01-01,2022-01-06 22:00:00,7.4046,2317.6398,2318,192394,196.74700,197.532000
3,4,511,Cloud Armor,262.0000,Requests,us-central1,86.48,27.19,8.712617e+10,8.792112e+10,2022-01-01,2022-01-05 07:00:00,9.1351,2393.3962,2393,198619,87.12617,87.921118
4,5,666,Cloud Tasks,232.0000,Requests,asia-east1,99.56,51.72,4.219470e+11,4.220110e+11,2022-01-01,2022-01-03 15:00:00,4.7032,1091.1424,1091,90553,421.94700,422.011000

In [56]:
df = df.drop(columns=['network_inbound_bytes', 'network_outbound_bytes','id'])

In [57]:
df.to_csv('../data/cleaned_cloud_billings.csv', index=False)